# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact-py/main/dbos/dbos-config.schema.json

name: cdm-ocr-service
language: python
runtimeConfig:
  start:
    - "fastapi run ocr_service/main.py"
database:
  app_db_name: ${POSTGRES_DB_NAME}
  hostname: ${POSTGRES_DB_HOST}
  port: 5432
  username: ${POSTGRES_DB_USER}
  password: ${POSTGRES_DB_PASSWORD}
telemetry:
  logs:
    logLevel: INFO
